token:
  expiration_time: 864000000
  secret: '{cipher}AQAq842tLW/j30eMaYjVHEuA5JgaDr9h8xEPEqn93xDz7l7/634vI/CwqrxuztBrQ0eWvnKaVCT3hi9khx/24E+lQ04ZhcGqTokMDSAc0ydrManAdQNPkWJh9LSBYANblQ9tGs0hdHBBcDKXHfoZmDeCNee4Di0QnJP7jSCpRKYYPZMVXyV5lUEnpFUXmoYD48Rk+QfnXQrZRdWinEX342B5f7ycqId4Z12G8lQLHs+RSHraiKV7tBiR3xWTB4Lb07BhmaXypC+uiiM6wHfOisysTQRkNYLxxhRuT7f9y+yjF09rgx7v+/jpP/WZNVm6U51eZlFOWeZyx+4O27NCRg0AW8CW9oyyz8a5Ew8zJN52IaugcaUTKIjFvblCq1B3r71nr9+iDuB2AD5xUTbcVWHyiiiEJdRoHurmQNRCMOO05Q=='

gateway:
  ip: 127.0.0.1
