token:
  expiration_time: 864000000
  secret: '{cipher}AQAq842tLW/j30eMaYjVHEuA5JgaDr9h8xEPEqn93xDz7l7/634vI/CwqrxuztBrQ0eWvnKaVCT3hi9khx/24E+lQ04ZhcGqTokMDSAc0ydrManAdQNPkWJh9LSBYANblQ9tGs0hdHBBcDKXHfoZmDeCNee4Di0QnJP7jSCpRKYYPZMVXyV5lUEnpFUXmoYD48Rk+QfnXQrZRdWinEX342B5f7ycqId4Z12G8lQLHs+RSHraiKV7tBiR3xWTB4Lb07BhmaXypC+uiiM6wHfOisysTQRkNYLxxhRuT7f9y+yjF09rgx7v+/jpP/WZNVm6U51eZlFOWeZyx+4O27NCRg0AW8CW9oyyz8a5Ew8zJN52IaugcaUTKIjFvblCq1B3r71nr9+iDuB2AD5xUTbcVWHyiiiEJdRoHurmQNRCMOO05Q=='

gateway:
  ip: 127.0.0.1

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCEOp75wvKQhwHOpjb/TXTFyLvc0QW9VrmqMglP/Bc3XxpBNaygWQlebMujh8YQgrmavtx/QqkxgSKfWevKLKqCf9d/tU6F74BTj53yA15bdCEkyabB/Gf28UPnwa0FE7+amULfMV0xooUMtmg9rSyaoZX7pfRmYk9tISMw0y2Zd6h7WJq07pZxIBpNutbeUqLzG1BnCuj3rd+5hTG8d3uEQsKt7hqZ75V6NhoMfEdlbHr3laaKb6tnK+i0AV01lF0fBGk7FxAWXK3XCuvZqVbqF++46PJnGMxraKE08g5TTxV1OSCGTnbnoOzm0Tw5kmxy4TxIv+nu88Ak7TqWe7U8BmO+KkcQuMrEI2WdtVD/vuuHe3cE9F294516l7XXlh8='
    # password: '{cipher}f181333e2725e5e4d296b04894c5533d4f51f5556569829ffbd4c25fffbfa21f'

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is empty.